#ifndef CONTINENTALFUZZY_EXPORT_H
#define CONTINENTALFUZZY_EXPORT_H

#include <QtCore/QtGlobal>

#if defined(MAKE_CONTINENTALFUZZY_LIB)
#  define CONTINENTALFUZZY_EXPORT_DECL Q_DECL_EXPORT
#else
#  define CONTINENTALFUZZY_EXPORT_DECL Q_DECL_IMPORT
#endif

#endif // CONTINENTALFUZZY_EXPORT_H


